# Generated by Django 4.2.3 on 2023-07-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=20)),
                ("user_password", models.CharField(max_length=20)),
                ("user_mail", models.CharField(max_length=20)),
                ("user_phone", models.CharField(max_length=20)),
            ],
        ),
    ]
