# Generated by Django 4.2.3 on 2023-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='passed_number',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='submission_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
